import { useMemo, useState, useEffect } from 'react';
import './App.css';
import Sidebar from './components/Sidebar';
import TopBar from './components/TopBar';
import StatsRow from './components/StatsRow';
import FieldInventoryPanel from './components/FieldInventoryPanel';
import SoilLookupPanel from './components/SoilLookupPanel';
import YieldChartPanel from './components/YieldChartPanel';
import FarmCreationPanel from './components/FarmCreationPanel';
import FarmEditPanel from './components/FarmEditPanel';
import ThemeConfigurationPanel from './components/ThemeConfigurationPanel';
import FieldCreationPanel from './components/FieldCreationPanel';
import { useTranslation } from 'react-i18next';

// --- FIREBASE IMPORTS ---
import { db } from './firebase'; 
import { collection, onSnapshot, addDoc, updateDoc, deleteDoc, doc } from 'firebase/firestore';

const LIGHT_THEME_DEFAULTS = {
  mode: 'light',
  primary: '#2e7d32',
  sidebar: '#1b5e20',
  background: '#f8faf8',
  panel: '#ffffff',
};

const DARK_THEME_DEFAULTS = {
  mode: 'dark',
  primary: '#66bb6a',
  sidebar: '#0f3d12',
  background: '#0f1410',
  panel: '#1a241a',
};

function hexToRgb(hexColor) {
  if (!hexColor) {
    return null;
  }

  const hex = hexColor.replace('#', '');
  if (!/^[0-9A-Fa-f]{6}$/.test(hex)) {
    return null;
  }

  return {
    r: Number.parseInt(hex.slice(0, 2), 16),
    g: Number.parseInt(hex.slice(2, 4), 16),
    b: Number.parseInt(hex.slice(4, 6), 16),
  };
}

function withAlpha(hexColor, alpha) {
  const rgb = hexToRgb(hexColor);
  if (!rgb) {
    return `rgba(0, 0, 0, ${alpha})`;
  }

  return `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${alpha})`;
}

function getAccessibleTextColor(hexColor) {
  const rgb = hexToRgb(hexColor);
  if (!rgb) {
    return '#ffffff';
  }

  const luminance = (0.299 * rgb.r + 0.587 * rgb.g + 0.114 * rgb.b) / 255;
  return luminance > 0.6 ? '#172317' : '#ffffff';
}

function getThemeDefaultsByMode(mode) {
  return mode === 'dark' ? DARK_THEME_DEFAULTS : LIGHT_THEME_DEFAULTS;
}

function buildThemeVariables(theme) {
  const isDark = theme.mode === 'dark';
  const sidebarText = getAccessibleTextColor(theme.sidebar);

  return {
    '--farm-green-main': theme.primary,
    '--farm-green-dark': theme.sidebar,
    '--farm-green-soft': withAlpha(theme.primary, isDark ? 0.2 : 0.12),
    '--bg-main': theme.background,
    '--panel-bg': theme.panel,
    '--panel-border': isDark ? '#334033' : '#dce3dc',
    '--panel-divider': isDark ? '#2a332a' : '#eeeeee',
    '--surface-alt': isDark ? '#202b20' : '#f9faf9',
    '--surface-alt-2': isDark ? '#1a231a' : '#fafbfa',
    '--input-bg': isDark ? '#1e2a1f' : '#ffffff',
    '--input-border': isDark ? '#3a473a' : '#dce3dc',
    '--text-main': isDark ? '#e2ebe2' : '#2c312c',
    '--text-muted': isDark ? '#a5b2a5' : '#6a736a',
    '--heading-main': isDark ? '#f5f7f5' : '#111111',
    '--danger-bg': isDark ? '#3b2323' : '#fff2f2',
    '--danger-border': isDark ? '#7d4141' : '#f1d2d2',
    '--danger-text': isDark ? '#ffb8b8' : '#8d2f2f',
    '--chart-grid': isDark ? '#374437' : '#eeeeee',
    '--chart-cursor': isDark ? 'rgba(102, 187, 106, 0.16)' : '#f1f8f1',
    '--sidebar-text': sidebarText,
    '--sidebar-text-muted': withAlpha(sidebarText, 0.78),
    '--sidebar-hover-bg': withAlpha(sidebarText, 0.12),
  };
}

// App is intentionally thin: it composes page-level sections and only keeps
// truly global UI state (currently the active sidebar tab).
function App() {
  const { t } = useTranslation();
  const [activeTab, setActiveTab] = useState('overview');
  const [farms, setFarms] = useState([]);
  const [theme, setTheme] = useState(LIGHT_THEME_DEFAULTS);

  const themeVariables = useMemo(() => buildThemeVariables(theme), [theme]);

  // --- FIREBASE REAL-TIME DATABASE CONNECTION ---
  useEffect(() => {
    const farmsCollection = collection(db, 'farms');
    
    // onSnapshot listens for any changes in the database and updates your app instantly
    const unsubscribe = onSnapshot(farmsCollection, (snapshot) => {
      const farmsData = snapshot.docs.map(doc => ({
        id: doc.id, // Firebase generates a unique string ID for us
        ...doc.data()
      }));
      setFarms(farmsData);
    });

    return () => unsubscribe(); // Cleanup when the app closes
  }, []);

  // --- FIREBASE WRITE FUNCTIONS ---
  const handleCreateFarm = async (newFarm) => {
    try {
      // Strip out the random ID generated by the frontend, Firebase makes its own
      const { id, ...farmData } = newFarm; 
      await addDoc(collection(db, 'farms'), farmData);
    } catch (error) {
      console.error("Error saving to cloud: ", error);
    }
  };

  const handleUpdateFarm = async (farmId, updatedData) => {
    try {
      const farmRef = doc(db, 'farms', farmId);
      await updateDoc(farmRef, updatedData);
    } catch (error) {
      console.error("Error updating cloud: ", error);
    }
  };

  const handleDeleteFarm = async (farmId) => {
    try {
      const farmRef = doc(db, 'farms', farmId);
      await deleteDoc(farmRef);
    } catch (error) {
      console.error("Error deleting from cloud: ", error);
    }
  };

  // --- THEME HANDLERS ---
  const handleThemeModeChange = (nextMode) => {
    setTheme(getThemeDefaultsByMode(nextMode));
  };

  const handleThemeColorChange = (colorKey, colorValue) => {
    setTheme((previous) => ({
      ...previous,
      [colorKey]: colorValue,
    }));
  };

  const handleThemeReset = () => {
    setTheme(getThemeDefaultsByMode(theme.mode));
  };

  const getPageMeta = () => {
    switch (activeTab) {
      case 'farm-create':
        return {
          title: 'Farm Setup',
          subtitle: 'Fill the basics and draw your farm border on the map.',
        };
      case 'farm-edit':
        return {
          title: t('tabs.farm_edit'),
          subtitle: 'Edit or delete existing farms.',
        };
      case 'overview':
        return {
          title: 'Project Overview',
          subtitle: 'Connected to Live Database',
        };
      case 'configuration':
        return {
          title: 'Theme Playground',
          subtitle: 'Try your own colors and quickly switch dark and light mode.',
        };
      case 'field-create':
        return {
          title: 'Field Setup',
          subtitle: 'Draw field boundaries and assign crop & soil properties.',
        };
      default:
        return {
          title: 'Dashboard',
          subtitle: 'This section is under development.',
        };
    }
  };

  const pageMeta = getPageMeta();

  return (
    <div className={`layout ${theme.mode === 'dark' ? 'theme-dark' : 'theme-light'}`} style={themeVariables}>
      <Sidebar activeTab={activeTab} setActiveTab={setActiveTab} />

      <main className="main-panel">
        <TopBar />

        <div className="dashboard-container">
          <div className="page-header">
            <h2>{pageMeta.title}</h2>
            <p className="page-subtitle">
              <span className="page-subtitle-dot">●</span>
              {pageMeta.subtitle}
            </p>
          </div>

          {activeTab === 'overview' && (
            <>
              {/* Passed the live Firebase 'farms' data down to StatsRow */}
              <StatsRow farms={farms} />

              <div className="content-grid">
                {/* Passed the live Firebase 'farms' data down to FieldInventoryPanel */}
                <FieldInventoryPanel farms={farms} />

                <div className="panel-column">
                  <SoilLookupPanel farms={farms} />
                  <YieldChartPanel farms={farms} />
                </div>
              </div>
            </>
          )}

          {activeTab === 'farm-create' && (
            <FarmCreationPanel onCreateFarm={handleCreateFarm} farms={farms} />
          )}

          {activeTab === 'farm-edit' && (
            <FarmEditPanel
              farms={farms}
              onUpdateFarm={handleUpdateFarm}
              onDeleteFarm={handleDeleteFarm}
            />
          )}

          {activeTab === 'configuration' && (
            <ThemeConfigurationPanel
              theme={theme}
              onModeChange={handleThemeModeChange}
              onColorChange={handleThemeColorChange}
              onResetTheme={handleThemeReset}
            />
          )}

          {activeTab !== 'overview' && activeTab !== 'farm-create' && activeTab !== 'farm-edit' && activeTab !== 'configuration' && (
            <section className="panel">
              <div className="panel-header">This module is coming soon</div>
              <p>Use the Farm Setup tab to register a farm and draw its boundary polygon.</p>
            </section>
          )}
        </div>
      </main>
    </div>
  );
}

export default App;